export const DUMMY_RECOMMENDED = [
  {
    id: "1",
    image: "https://stailer.ro/files/B-FKBMWJCR/S163274355071-thumb.jpg",
    name: "Sebastian Bajan",
    title: "Tuns",
    distance: "1 km",
    address: "Strada Fermei 97, Popesti Leordeni",
    minPrice: 40,
    ratingsAverage: 4.5,
    ratingsQuantity: 100,
    availableSeats: 1,
  },
  {
    id: "2",
    image: "https://stailer.ro/files/B-SSNJXNUB/S163462396645-thumb.jpg",
    name: "Trattoria Monza",
    title: "Restaurant",
    distance: "2 km",
    address: "Strada Baba Novac, nr 15, Bucuresti",
    ratingsAverage: 4.3,
    ratingsQuantity: 20,
    availableSeats: 3,
  },
  {
    id: "3",
    name: "Carhaus",
    title: "Spălătorie auto",
    address: "Sos Straulesti 73-77, Bucuresti",
    distance: "3 km",
    image:
      "https://i0.wp.com/www.carhaus.ro/wp-content/uploads/2020/02/1Q2A7787-300x200.jpg",
    ratingsAverage: 4,
    ratingsQuantity: 170,
    availableSeats: 3,
  },
  {
    id: "4",
    name: "ITP Dristor",
    title: "ITP",
    address: "Intrarea Parului Nr. 4, Sector 3, Bucuresti",
    distance: "3 km",
    image: "https://www.itpdristor.ro/img/contact-page/contact-img.jpg",
    ratingsAverage: 4.5,
    ratingsQuantity: 120,
    availableSeats: 2,
  },
  {
    id: "5",
    name: "Serenity Welness",
    title: "Tuns",
    address: "Strada 8 martie 39, Mogosoaia",
    distance: "1 km",
    image: "https://stailer.ro/files/B-TYJBUYWL/S162090464739-thumb.jpg",
    ratingsAverage: 5,
    ratingsQuantity: 55,
    availableSeats: 1,
  },
  {
    id: "6",
    name: "Mandaloo Popesti Leordeni",
    title: "Restaurant",
    address: "Amurgului 34, Popesti-Leordeni",
    distance: "3 km",
    image: "http://www.mandaloo.ro/images/galerie/mandaloo_02_1920x1280.jpg",
    ratingsAverage: 4.5,
    ratingsQuantity: 75,
    availableSeats: 1,
  },
  {
    id: "7",
    name: "Thaico Spa Victoriei",
    title: "Masaj",
    address: "Str. Intrarea Sevastopol, nr. 1 Bucuresti",
    distance: "5 km",
    image:
      "https://thaicospa.ro/wp-content/uploads/2021/02/masaj-la-patru-maini.jpg",
    ratingsAverage: 5,
    ratingsQuantity: 210,
    availableSeats: 2,
  },
  {
    id: "8",
    name: "Novo Salon",
    title: "Pensat",
    address: "Strada Biruintei, nr 91, Bucuresti",
    distance: "3 km",
    image: "https://stailer.ro/files/B-GAXWLKXS/S163835923162-thumb.jpg",
    ratingsAverage: 4.5,
    ratingsQuantity: 130,
    availableSeats: 3,
  },
  {
    id: "9",
    name: "Thaico Spa Novotel",
    title: "Masaj",
    address: "Calea Victoriei 37B, Bucuresti",
    distance: "7 km",
    image:
      "https://thaicospa.ro/wp-content/uploads/2021/03/masaj-capilar-facial-e1524822913361.jpg",
    ratingsAverage: 4.5,
    ratingsQuantity: 150,
    availableSeats: 3,
  },
  {
    id: "10",
    name: "Neo Salon",
    title: "Pensat",
    address: "Bulevardul Bucureștii Noi 28, București",
    distance: "20 km",
    image: "https://neosalon.ro/wp-content/uploads/2017/11/1414_01.jpg",
    ratingsAverage: 4,
    ratingsQuantity: 15,
    availableSeats: 2,
  },
  {
    id: "11",
    name: "Brady Auto Center",
    title: "ITP",
    address: "B-dul Iuliu Maniu nr. 291, sector 6, Bucuresti",
    distance: "3 km",
    image:
      "https://bradytrade.ro/uploads/user-uploads/image/image/pages/ITP-service-Brady-Skoda-697x300.jpg",
    ratingsAverage: 3.5,
    ratingsQuantity: 15,
    availableSeats: 1,
  },
  {
    id: "12",
    name: "IDM CLub",
    title: "Biliard",
    address: "Splaiul Independentei 319B",
    distance: "5 km",
    image: "http://www.idmclub.ro/images/ICR_Bil.jpg",
    ratingsAverage: 4.5,
    ratingsQuantity: 15,
    availableSeats: 2,
  },
  {
    id: "13",
    name: "TSG Service",
    title: "Spălătorie auto",
    address: "Str. Valea Oltului, Nr. 73-75, Sector 6, București",
    distance: "2.5 km",
    image:
      "https://www.itpautobaicului.ro/images/default/spalatorie-auto-02.jpg",
    ratingsAverage: 4.5,
    ratingsQuantity: 35,
    availableSeats: 3,
  },
  {
    id: "14",
    name: "IDM Club",
    title: "Ping Pong",
    address: "http://www.idmclub.ro/images/ICR_Bil.jpg",
    distance: "2 km",
    image: "http://www.idmclub.ro/images/tenis-de-masa.jpg",
    ratingsAverage: 4,
    ratingsQuantity: 20,
    availableSeats: 2,
  },
  {
    id: "15",
    name: "IDM Club",
    title: "Ping Pong",
    address: "http://www.idmclub.ro/images/ICR_Bil.jpg",
    distance: "2 km",
    image: "http://www.idmclub.ro/images/tenis-de-masa.jpg",
    ratingsAverage: 4,
    ratingsQuantity: 20,
    availableSeats: 2,
  },
  {
    id: "16",
    name: "IDM Club",
    title: "Ping Pong",
    address: "http://www.idmclub.ro/images/ICR_Bil.jpg",
    distance: "2 km",
    image: "http://www.idmclub.ro/images/tenis-de-masa.jpg",
    ratingsAverage: 4,
    ratingsQuantity: 20,
    availableSeats: 2,
  },
  {
    id: "17",
    name: "IDM Club",
    title: "Ping Pong",
    address: "http://www.idmclub.ro/images/ICR_Bil.jpg",
    distance: "2 km",
    image: "http://www.idmclub.ro/images/tenis-de-masa.jpg",
    ratingsAverage: 4,
    ratingsQuantity: 20,
    availableSeats: 2,
  },
  {
    id: "18",
    name: "IDM Club",
    title: "Ping Pong",
    address: "http://www.idmclub.ro/images/ICR_Bil.jpg",
    distance: "2 km",
    image: "http://www.idmclub.ro/images/tenis-de-masa.jpg",
    ratingsAverage: 4,
    ratingsQuantity: 20,
    availableSeats: 2,
  },
];
